/// Expands a recurring item into concrete occurrences for a date range. Pure function over the series and
/// its per-occurrence overrides; occurrences are never stored.
///
/// Rules: `interval` counts days/weeks/months/years; weekly rules use ISO weeks (Monday first) and
/// `byWeekday` (default: the weekday of the start date); monthly rules use `byMonthday` (default: the day of
/// the start date) and clamp to the month length ("каждое 31-е" falls on the last day of shorter months);
/// yearly rules keep month and day and clamp Feb 29 to Feb 28 in common years. `count` includes the first
/// occurrence; `until` is inclusive.
public enum RecurrenceExpander {
    public enum State: String, Sendable {
        case open, done, skipped
    }

    public struct Occurrence: Hashable, Sendable {
        /// The date the rule generated; the key under which overrides are stored.
        public var originalDate: LocalDate
        /// Where the occurrence appears (differs from `originalDate` when it was moved).
        public var date: LocalDate
        public var time: LocalTime?
        public var state: State
        public var wasMoved: Bool
    }

    private static let maxPeriods = 20_000

    public static func occurrences(
        of item: Item, from: LocalDate, through: LocalDate, exceptions: [ItemException] = []
    ) -> [Occurrence] {
        guard let rule = item.recurrence, let start = item.date, from <= through else { return [] }
        let overrides = Dictionary(
            exceptions.filter { $0.itemID == item.id }.map { ($0.occDate, $0) },
            uniquingKeysWith: { _, last in last }
        )

        var result: [Occurrence] = []
        for date in ruleDates(rule: rule, start: start, from: from, through: through) {
            switch overrides[date]?.action {
            case .skip:
                result.append(Occurrence(originalDate: date, date: date, time: item.time, state: .skipped, wasMoved: false))
            case .done:
                result.append(Occurrence(originalDate: date, date: date, time: item.time, state: .done, wasMoved: false))
            case .moved:
                break // shown at its new date below
            case nil:
                result.append(Occurrence(originalDate: date, date: date, time: item.time, state: .open, wasMoved: false))
            }
        }
        for exception in overrides.values where exception.action == .moved {
            guard let movedDate = exception.movedDate, movedDate >= from, movedDate <= through else { continue }
            result.append(Occurrence(
                originalDate: exception.occDate, date: movedDate, time: exception.movedTime ?? item.time,
                state: .open, wasMoved: true
            ))
        }
        return result.sorted {
            if $0.date != $1.date { return $0.date < $1.date }
            return ($0.time?.minutesSinceMidnight ?? -1) < ($1.time?.minutesSinceMidnight ?? -1)
        }
    }

    // MARK: - Rule dates

    /// Dates generated by the rule within `from...through`, ascending.
    static func ruleDates(rule: Recurrence, start: LocalDate, from: LocalDate, through: LocalDate) -> [LocalDate] {
        let limit = min(through, rule.until ?? through)
        guard limit >= start, from <= limit else { return [] }
        let maxCount = rule.count ?? Int.max
        guard maxCount > 0 else { return [] }

        var result: [LocalDate] = []
        var emitted = 0
        var period = rule.count == nil ? firstPeriod(rule: rule, start: start, from: from) : 0
        var guardCounter = 0
        while guardCounter < maxPeriods {
            guardCounter += 1
            let dates = periodDates(rule: rule, start: start, period: period)
            if let first = dates.first, first > limit { break }
            if dates.isEmpty, period > 2 * 12 * 100 { break }
            for date in dates {
                if emitted >= maxCount { return result }
                emitted += 1
                if date > limit { return result }
                if date >= from { result.append(date) }
            }
            period += 1
        }
        return result
    }

    /// A period index at or before the first period that can contain `from` (only used without `count`).
    private static func firstPeriod(rule: Recurrence, start: LocalDate, from: LocalDate) -> Int {
        guard from > start else { return 0 }
        let k = max(1, rule.interval)
        switch rule.freq {
        case .daily:
            return max(0, start.days(until: from) / k)
        case .weekly:
            return max(0, start.startOfWeek.days(until: from.startOfWeek) / 7 / k)
        case .monthly:
            let months = (from.year * 12 + from.month) - (start.year * 12 + start.month)
            return max(0, months / k)
        case .yearly:
            return max(0, (from.year - start.year) / k)
        }
    }

    /// The dates of the `period`-th repeat step, ascending and never earlier than `start`.
    private static func periodDates(rule: Recurrence, start: LocalDate, period: Int) -> [LocalDate] {
        let k = max(1, rule.interval)
        switch rule.freq {
        case .daily:
            return [start.adding(days: period * k)]
        case .weekly:
            let weekStart = start.startOfWeek.adding(days: 7 * period * k)
            let days = Set(rule.byWeekday ?? [start.weekday]).sorted()
            return days.map { weekStart.adding(days: $0.rawValue - 1) }.filter { $0 >= start }
        case .monthly:
            let base = start.firstOfMonth.adding(months: period * k)
            let day = min(max(1, rule.byMonthday ?? start.day), base.daysInMonth)
            let date = base.adding(days: day - 1)
            return date >= start ? [date] : []
        case .yearly:
            return [start.adding(months: 12 * period * k)]
        }
    }
}
